/* prettier-ignore */
// ==== This file is auto-generated by @o7/vite-plugin-gql. Do not edit. ====
// <files>["src/main.ts","src/file2.ts"]</files>
declare module '$gql' {
	//#region main.ts
	export default function gql(
		query: '\n\t\t\tquery {\n\t\t\t\tallFilms {\n\t\t\t\t\tfilms {\n\t\t\t\t\t\ttitle\n\t\t\t\t\t\tdirector\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t',
		variables?: undefined,
	): Promise<
		| {
				allFilms?:
					| {
							films?:
								| Array<
										| {
												title?: string | null | undefined;
												director?: string | null | undefined;
										  }
										| null
										| undefined
								  >
								| null
								| undefined;
					  }
					| null
					| undefined;
		  }
		| null
		| undefined
	>;
	export default function gql(
		query: '\n\t\t\tquery ($id: ID!) {\n\t\t\t\tstarship(id: $id) {\n\t\t\t\t\tname\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t',
		variables: { id: string },
	): Promise<
		| {
				starship?:
					| { name?: string | null | undefined; id: string }
					| null
					| undefined;
		  }
		| null
		| undefined
	>;
	//#region file2.ts
	export default function gql(
		query: '\n\t\t\tquery {\n\t\t\t\tallFilms {\n\t\t\t\t\tfilms {\n\t\t\t\t\t\tid\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t',
		variables?: undefined,
	): Promise<
		| {
				allFilms?:
					| {
							films?:
								| Array<{ id: string } | null | undefined>
								| null
								| undefined;
					  }
					| null
					| undefined;
		  }
		| null
		| undefined
	>;
	export default function gql(
		query: '\n\t\t\tquery ($id: ID!) {\n\t\t\t\tstarship(id: $id) {\n\t\t\t\t\tname\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t',
		variables: { id: string },
	): Promise<
		| {
				starship?:
					| { name?: string | null | undefined; id: string }
					| null
					| undefined;
		  }
		| null
		| undefined
	>;
}
