/* prettier-ignore */
// ==== This file is auto-generated by @o7/vite-plugin-gql. Do not edit. ====
// <files>["src/file2.ts","src/main.ts"]</files>
declare module '$gql' {
	export type GraphQLPromise<T> = Promise<{
		data?: T;
		errors?: Array<GraphQLError>;
	}> & {
		with(overrides: { url?: string; headers?: HeadersInit }): GraphQLPromise<T>;
	};
	export type GraphQLError = {
		message: string;
		locations?: Array<{
			line: number;
			column: number;
		}>;
		path?: Array<string | number>;
		extensions?: Record<string, unknown>;
	};
	//#region file2.ts
	export default function gql(
		query: '\n\t\t\tquery {\n\t\t\t\tallFilms {\n\t\t\t\t\tfilms {\n\t\t\t\t\t\tid\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t',
		variables?: undefined,
	): GraphQLPromise<
		| {
				allFilms?:
					| {
							films?:
								| Array<{ id: string } | null | undefined>
								| null
								| undefined;
					  }
					| null
					| undefined;
		  }
		| null
		| undefined
	>;
	export default function gql(
		query: '\n\t\t\tquery ($id: ID!) {\n\t\t\t\tstarship(id: $id) {\n\t\t\t\t\tname\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t',
		variables: { id: string },
	): GraphQLPromise<
		| {
				starship?:
					| { name?: string | null | undefined; id: string }
					| null
					| undefined;
		  }
		| null
		| undefined
	>;
	//#region main.ts
	export default function gql(
		query: '\n\t\t\tquery {\n\t\t\t\tallFilms {\n\t\t\t\t\tfilms {\n\t\t\t\t\t\ttitle\n\t\t\t\t\t\tdirector\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t',
		variables?: undefined,
	): GraphQLPromise<
		| {
				allFilms?:
					| {
							films?:
								| Array<
										| {
												title?: string | null | undefined;
												director?: string | null | undefined;
										  }
										| null
										| undefined
								  >
								| null
								| undefined;
					  }
					| null
					| undefined;
		  }
		| null
		| undefined
	>;
	export default function gql(
		query: '\n\t\t\tquery ($id: ID!) {\n\t\t\t\tstarship(id: $id) {\n\t\t\t\t\tname\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t',
		variables: { id: string },
	): GraphQLPromise<
		| {
				starship?:
					| { name?: string | null | undefined; id: string }
					| null
					| undefined;
		  }
		| null
		| undefined
	>;
}
